In [9]:
from scipy.stats import t
from scipy.linalg import pinvh as inv
from numpy.linalg import lstsq
import numpy.matlib as mb
import ipywidgets as widgets
import math as mt
import numpy as np
import pandas as pd
import re   

# Calibração

In [10]:
def MMQ(y, mx):
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados
  return (coef)

In [11]:
def RMSE(yReal, yEstimado): # root-mean-square deviation
  residuos = np.sum(np.power((yReal - yEstimado),2))**0.5
  return(residuos)

In [12]:
def calcular_r2(y_true, y_pred):
    """
    Calcula o coeficiente de determinação R².
    
    Parâmetros:
    y_true: array-like, Valores observados (reais).
    y_pred: array-like, Valores preditos pelo modelo.
    
    Retorno:
    r2: float, Coeficiente de determinação R².
    """
    # Converter para arrays do NumPy, caso não sejam
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # Média dos valores observados
    y_mean = np.mean(y_true)
    
    # Soma dos quadrados dos resíduos (SSR)
    ss_res = np.sum((y_true - y_pred) ** 2)
    
    # Soma total dos quadrados (SST)
    ss_tot = np.sum((y_true - y_mean) ** 2)
    
    # Cálculo de R²
    r2 = 1 - (ss_res / ss_tot)
    
    return r2

## Caso 1: Sistema de 1º Ordem sendo avaliado por diversas ordens

In [13]:
x = np.matrix([560,1423,2860,2960,3024,3200,3490,3740,3915,4095])
y = np.matrix([3,21,222,299,325,550,805,1270,2022,4480])

In [14]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.78572301]] [[-1299.87552361]]
[[   3   21  222  299  325  550  805 1270 2022 4480]] 
 [[-859.87063987 -181.79168512  947.29227546 1025.86457612 1076.15084855
  1214.43809772 1442.29776965 1638.72852132 1776.23004749 1917.66018869]]
3164.4674332954614
0.4100150852286062


In [15]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))  #x^2+x+c

[[0.00049003]] [[-1.30697345]] [[-0.00110103]]
[[   3   21  222  299  325  550  805 1270 2022 4480]] 
 [[-578.23367099 -867.55383044  270.28212525  424.78066789  528.8030617
   835.56339775 1407.24305867 1966.2240378  2393.95650346 2865.22264106]]
2204.9663815910108
0.7135534533119234


In [16]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[1.65295243e-07]] [[-0.00047603]] [[-2.95578927e-07]] [[-1.49169351e-10]]
[[   3   21  222  299  325  550  805 1270 2022 4480]] 
 [[-120.25401144 -487.62908903  -26.8582313   116.05584592  217.86826637
   541.86834672 1228.393035   1988.70486955 2622.53335872 3368.16085431]]
1635.0725882648014
0.8424879725254295
